name: flutter_notification_wrapper
description: A comprehensive Flutter package that provides a unified interface for Firebase Cloud Messaging and AwesomeNotifications with advanced features like background handling, action buttons, scheduling, and more.
version: 0.3.0
homepage: https://github.com/antsf/flutter_notification_wrapper
repository: https://github.com/antsf/flutter_notification_wrapper.git
issue_tracker: https://github.com/antsf/flutter_notification_wrapper/issues
documentation: https://github.com/antsf/flutter_notification_wrapper/wiki

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.19.3'

dependencies:
  awesome_notifications: ^0.10.1
  firebase_analytics: ^11.4.5
  firebase_core: ^3.6.0
  firebase_messaging: ^15.2.5
  flutter:
    sdk: flutter
  meta: ^1.9.1

dev_dependencies:
  build_runner: ^2.4.0
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  mockito: ^5.4.0
  test: ^1.24.0

flutter:
  uses-material-design: true

topics:
  - notifications
  - firebase
  - messaging
  - push-notifications
  - awesome-notifications
